"""
Routing backend implementations for the proxy route service.

Contains cgproxy, redsocks, and env-based routing methods.
"""

import json
import logging
import subprocess
import tempfile
from pathlib import Path

from .constants import (
    IPTABLES_CHAIN,
    REDSOCKS_CONFIG_DIR,
    REDSOCKS_CONFIG_FILE,
)

logger = logging.getLogger(__name__)

# Backend-specific timeouts (seconds)
TIMEOUT_APP_RUN = 5  # cgproxy <app> launch


def setup_cgproxy(run_privileged, proxy_host: str, proxy_port: int, app_paths: list[str]) -> bool:
    """Setup cgproxy for SOCKS5 proxy routing."""
    config = {
        "comment": "Generated by SplitWire-Turkey for ByeDPI",
        "port": proxy_port,
        "socks5": f"{proxy_host}:{proxy_port}",
        "program_noproxy": [],
        "program_proxy": app_paths,
        "cgroup_noproxy": ["/"],
        "cgroup_proxy": [],
        "enable_gateway": False,
        "enable_dns": True,
        "enable_udp": True,
        "enable_tcp": True,
        "enable_ipv6": True,
        "table": 10008,
        "fwmark": 0x9974,
        "cgroup_root": "/sys/fs/cgroup",
    }

    config_content = json.dumps(config, indent=2)
    cgproxy_config = Path("/etc/cgproxy/config.json")

    try:
        result = run_privileged(["mkdir", "-p", "/etc/cgproxy"])
        if not result.success:
            return False

        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            f.write(config_content)
            tmp_path = f.name

        result = run_privileged(["cp", tmp_path, str(cgproxy_config)])
        Path(tmp_path).unlink(missing_ok=True)

        if not result.success:
            return False

        logger.info("cgproxy configured for SOCKS5 proxy")
        return True

    except Exception as e:
        logger.exception(f"Failed to setup cgproxy: {e}")
        return False


def cleanup_cgproxy(run_privileged) -> None:
    """Remove cgproxy configuration."""
    run_privileged(["rm", "-f", "/etc/cgproxy/config.json"])


def run_via_cgproxy(shell, app_path: str, args: list[str] | None = None) -> bool:
    """Run app through cgproxy."""
    if not shell.command_exists("cgproxy"):
        logger.error("cgproxy not installed")
        return False

    cmd = ["cgproxy", app_path]
    if args:
        cmd.extend(args)

    result = shell.run(cmd, timeout=TIMEOUT_APP_RUN)
    return result.success


def setup_redsocks(run_privileged, proxy_host: str, proxy_port: int) -> bool:
    """Setup redsocks for transparent proxying."""
    config_content = (
        "base {\n"
        "    log_debug = off;\n"
        "    log_info = on;\n"
        '    log = "syslog:daemon";\n'
        "    daemon = on;\n"
        "    redirector = iptables;\n"
        "}\n\n"
        "redsocks {\n"
        "    local_ip = 127.0.0.1;\n"
        "    local_port = 12345;\n"
        f"    ip = {proxy_host};\n"
        f"    port = {proxy_port};\n"
        "    type = socks5;\n"
        "}\n"
    )

    try:
        result = run_privileged(["mkdir", "-p", str(REDSOCKS_CONFIG_DIR)])
        if not result.success:
            return False

        with tempfile.NamedTemporaryFile(mode="w", suffix=".conf", delete=False) as f:
            f.write(config_content)
            tmp_path = f.name

        result = run_privileged(["cp", tmp_path, str(REDSOCKS_CONFIG_FILE)])
        Path(tmp_path).unlink(missing_ok=True)

        if not result.success:
            return False

        logger.info("redsocks configured")
        return True

    except Exception as e:
        logger.exception(f"Failed to setup redsocks: {e}")
        return False


def cleanup_redsocks(run_privileged) -> None:
    """Remove redsocks configuration."""
    remove_iptables_rules(run_privileged)
    run_privileged(["rm", "-f", str(REDSOCKS_CONFIG_FILE)])


def add_iptables_rules(run_privileged) -> None:
    """Add iptables rules for redsocks."""
    logger.info("[PROXY] Adding iptables rules for redsocks...")
    commands = [
        f"iptables -t nat -N {IPTABLES_CHAIN}",
        f"iptables -t nat -A {IPTABLES_CHAIN} -d 0.0.0.0/8 -j RETURN",
        f"iptables -t nat -A {IPTABLES_CHAIN} -d 10.0.0.0/8 -j RETURN",
        f"iptables -t nat -A {IPTABLES_CHAIN} -d 127.0.0.0/8 -j RETURN",
        f"iptables -t nat -A {IPTABLES_CHAIN} -d 169.254.0.0/16 -j RETURN",
        f"iptables -t nat -A {IPTABLES_CHAIN} -d 172.16.0.0/12 -j RETURN",
        f"iptables -t nat -A {IPTABLES_CHAIN} -d 192.168.0.0/16 -j RETURN",
        f"iptables -t nat -A {IPTABLES_CHAIN} -d 224.0.0.0/4 -j RETURN",
        f"iptables -t nat -A {IPTABLES_CHAIN} -d 240.0.0.0/4 -j RETURN",
        f"iptables -t nat -A {IPTABLES_CHAIN} -p tcp -j REDIRECT --to-ports 12345",
        f"iptables -t nat -A OUTPUT -p tcp -j {IPTABLES_CHAIN}",
    ]

    for cmd in commands:
        logger.debug(f"[PROXY] Running iptables: {cmd}")
        result = run_privileged(cmd.split())
        if not result.success:
            logger.warning(f"[PROXY] iptables rule may have failed: {result.stderr}")
    logger.info("[PROXY] iptables rules added")


def remove_iptables_rules(run_privileged) -> None:
    """Remove iptables rules."""
    logger.info("[PROXY] Removing iptables rules...")
    commands = [
        f"iptables -t nat -D OUTPUT -p tcp -j {IPTABLES_CHAIN}",
        f"iptables -t nat -F {IPTABLES_CHAIN}",
        f"iptables -t nat -X {IPTABLES_CHAIN}",
    ]

    for cmd in commands:
        logger.debug(f"[PROXY] Running iptables: {cmd}")
        result = run_privileged(cmd.split())
        if not result.success:
            logger.debug(f"[PROXY] iptables rule may not exist: {result.stderr}")
    logger.info("[PROXY] iptables rules removed")


def run_via_env(
    proxy_host: str,
    proxy_port: int,
    app_path: str,
    args: list[str] | None = None,
) -> bool:
    """Run app with proxy environment variables."""
    proxy_url = f"socks5://{proxy_host}:{proxy_port}"

    env = {
        **dict(subprocess.os.environ),
        "http_proxy": proxy_url,
        "https_proxy": proxy_url,
        "HTTP_PROXY": proxy_url,
        "HTTPS_PROXY": proxy_url,
        "all_proxy": proxy_url,
        "ALL_PROXY": proxy_url,
    }

    cmd = [app_path]
    if args:
        cmd.extend(args)

    try:
        subprocess.Popen(cmd, env=env, start_new_session=True)
        return True
    except Exception as e:
        logger.error(f"Failed to run app: {e}")
        return False
