"""DNS backend helpers for systemd-resolved, NetworkManager, and manual."""

import re
import tempfile
from pathlib import Path

from .constants import RESOLVED_CONF_DIR, SPLITWIRE_RESOLVED_CONF
from .models import DoHMode


def build_resolved_config(primary: str, secondary: str, doh_mode: DoHMode) -> str:
    """Build systemd-resolved configuration content."""
    config_lines = [
        "# Generated by SplitWire-Turkey",
        "# Do not edit manually",
        "[Resolve]",
        f"DNS={primary} {secondary}",
        "FallbackDNS=1.1.1.1 8.8.8.8",
        "Domains=~.",
        "DNSSEC=allow-downgrade",
    ]

    if doh_mode == DoHMode.STRICT:
        config_lines.append("DNSOverTLS=yes")
    elif doh_mode == DoHMode.OPPORTUNISTIC:
        config_lines.append("DNSOverTLS=opportunistic")
    else:
        config_lines.append("DNSOverTLS=no")

    return "\n".join(config_lines) + "\n"


def write_resolved_config(content: str, run_privileged_fn, logger) -> bool:
    """Write resolved config via temp file and privileged copy."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".conf", delete=False) as f:
        f.write(content)
        tmp_path = f.name

    result = run_privileged_fn(["cp", tmp_path, str(SPLITWIRE_RESOLVED_CONF)])
    Path(tmp_path).unlink(missing_ok=True)

    if not result.success:
        logger.error(f"Failed to write config: {result.stderr}")
        return False

    run_privileged_fn(["chmod", "644", str(SPLITWIRE_RESOLVED_CONF)])
    return True


def apply_systemd_resolved(
    primary: str,
    secondary: str,
    doh_mode: DoHMode,
    run_privileged_fn,
    logger,
) -> bool:
    """Apply DNS using systemd-resolved."""
    logger.info("Applying DNS via systemd-resolved")
    try:
        result = run_privileged_fn(["mkdir", "-p", str(RESOLVED_CONF_DIR)])
        if not result.success:
            logger.error(f"Failed to create config dir: {result.stderr}")
            return False

        config_content = build_resolved_config(primary, secondary, doh_mode)
        if not write_resolved_config(config_content, run_privileged_fn, logger):
            return False

        result = run_privileged_fn(["systemctl", "restart", "systemd-resolved"])
        if not result.success:
            logger.error(f"Failed to restart resolved: {result.stderr}")
            return False

        logger.info("systemd-resolved configured successfully")
        return True

    except Exception as e:
        logger.exception(f"Failed to apply systemd-resolved: {e}")
        return False


def remove_systemd_resolved(run_privileged_fn, logger) -> bool:
    """Remove systemd-resolved configuration."""
    try:
        if SPLITWIRE_RESOLVED_CONF.exists():
            run_privileged_fn(["rm", "-f", str(SPLITWIRE_RESOLVED_CONF)])
        run_privileged_fn(["systemctl", "restart", "systemd-resolved"])
        return True
    except Exception as e:
        logger.warning(f"Failed to remove resolved config: {e}")
        return False


def apply_network_manager(primary: str, secondary: str, shell, run_privileged_fn, logger) -> bool:
    """Apply DNS using NetworkManager."""
    logger.info("Applying DNS via NetworkManager")
    try:
        connections = get_active_nm_connections(shell)
        if not connections:
            logger.error("No active network connections")
            return False

        for conn in connections:
            result = run_privileged_fn(
                [
                    "nmcli",
                    "connection",
                    "modify",
                    conn,
                    "ipv4.dns",
                    f"{primary} {secondary}",
                    "ipv4.ignore-auto-dns",
                    "yes",
                ]
            )
            if not result.success:
                logger.warning(f"Failed to modify connection {conn}")

        run_privileged_fn(["systemctl", "restart", "NetworkManager"])
        return True

    except Exception as e:
        logger.exception(f"Failed to apply NetworkManager DNS: {e}")
        return False


def get_active_nm_connections(shell) -> list[str]:
    """Get list of active NetworkManager connection names."""
    result = shell.run(
        [
            "nmcli",
            "-t",
            "-f",
            "NAME,TYPE,DEVICE",
            "connection",
            "show",
            "--active",
        ],
        timeout=10,
    )
    if not result.success:
        return []

    min_nm_fields = 3
    connections = []
    for line in result.stdout.strip().split("\n"):
        if line:
            parts = line.split(":")
            if len(parts) >= min_nm_fields:
                connections.append(parts[0])
    return connections


def apply_manual_dns(primary: str, secondary: str, run_privileged_fn, logger) -> bool:
    """Apply DNS by directly editing /etc/resolv.conf."""
    logger.info("Applying DNS via /etc/resolv.conf")
    try:
        resolv_content = (
            f"# Generated by SplitWire-Turkey\n"
            f"# Original settings backed up\n"
            f"nameserver {primary}\n"
            f"nameserver {secondary}\n"
        )

        with tempfile.NamedTemporaryFile(mode="w", delete=False) as f:
            f.write(resolv_content)
            tmp_path = f.name

        run_privileged_fn(["chattr", "-i", "/etc/resolv.conf"])
        result = run_privileged_fn(["cp", tmp_path, "/etc/resolv.conf"])
        Path(tmp_path).unlink(missing_ok=True)

        if not result.success:
            logger.error(f"Failed to write resolv.conf: {result.stderr}")
            return False

        run_privileged_fn(["chattr", "+i", "/etc/resolv.conf"])
        return True

    except Exception as e:
        logger.exception(f"Failed to apply manual DNS: {e}")
        return False


def restore_network_manager(shell, run_privileged_fn) -> None:
    """Restore NetworkManager to auto DNS."""
    result = shell.run(
        [
            "nmcli",
            "-t",
            "-f",
            "NAME",
            "connection",
            "show",
            "--active",
        ],
        timeout=10,
    )
    if result.success:
        for conn in result.stdout.strip().split("\n"):
            if conn:
                run_privileged_fn(
                    [
                        "nmcli",
                        "connection",
                        "modify",
                        conn,
                        "ipv4.dns",
                        "",
                        "ipv4.ignore-auto-dns",
                        "no",
                    ]
                )
        run_privileged_fn(["systemctl", "restart", "NetworkManager"])


def restore_manual_dns(backup_data: dict, run_privileged_fn) -> None:
    """Restore /etc/resolv.conf from backup data."""
    dns_servers = backup_data.get("dns_servers", [])
    if not dns_servers:
        return

    run_privileged_fn(["chattr", "-i", "/etc/resolv.conf"])

    content = "# Restored by SplitWire-Turkey\n"
    for server in dns_servers:
        content += f"nameserver {server}\n"
    for domain in backup_data.get("search_domains", []):
        content += f"search {domain}\n"

    with tempfile.NamedTemporaryFile(mode="w", delete=False) as f:
        f.write(content)
        tmp_path = f.name

    run_privileged_fn(["cp", tmp_path, "/etc/resolv.conf"])
    Path(tmp_path).unlink(missing_ok=True)


def parse_resolvectl_output(
    output: str,
) -> tuple[list[str], list[str], bool]:
    """Parse resolvectl status output for DNS info."""
    dns_servers: list[str] = []
    search_domains: list[str] = []
    doh_enabled = False

    for line in output.split("\n"):
        if "DNS Servers:" in line or "Current DNS Server:" in line:
            ips = re.findall(r"\d+\.\d+\.\d+\.\d+", line)
            dns_servers.extend(ips)
        if "DNS Domain:" in line:
            domains = line.split(":")[1].strip().split()
            search_domains.extend(domains)
        if "DNSOverTLS" in line and "yes" in line.lower():
            doh_enabled = True

    return dns_servers, search_domains, doh_enabled


def parse_resolv_conf(content: str) -> tuple[list[str], list[str]]:
    """Parse /etc/resolv.conf content."""
    dns_servers: list[str] = []
    search_domains: list[str] = []

    for line in content.split("\n"):
        if line.startswith("nameserver"):
            dns_servers.append(line.split()[1])
        if line.startswith("search"):
            search_domains.extend(line.split()[1:])

    return dns_servers, search_domains
